version: '3.8'

services:
  bot-psql:
    image: postgres:14.2
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
  bot: &web_base
    tty: true
    stdin_open: true
    command: sh /docker-entrypoint.sh
    build: ./docker
    links:
      - bot-psql
    ports:
      - 5000:5000
    volumes:
      - .:/app
      - bundle_cache:/app/vendor/bundle
    environment:
      DB_USER: dbuser
      DB_PASSWORD: dbpass
      DB_HOST: psql
      REDIS_URL: redis://redis:6379
  redis:
    image: redis
  ngrok: # curl localhost:4041/api/tunnels
    image: wernight/ngrok
    ports:
      - '4041:4040'
    command:
      - /bin/sh
      - -c
      - |
        ngrok http -bind-tls=true --authtoken $NGROK_AUTH --log=stdout bot:5000
    depends_on:
      - bot
volumes:
  bundle_cache:
